export const SUPA_BASE_CREDENTIONAL = {
  BASE_URL: 'https://onkcipwfrkveiovzjquu.supabase.co',
  BASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ua2NpcHdmcmt2ZWlvdnpqcXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA3OTAzNjEsImV4cCI6MjAzNjM2NjM2MX0.4tUaySOh7khUqCsniIZkYUjXTHXtE1L-XlovcBqNKZg'
}
